default_language_version:
  node: 12.18.2

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
    - id: eslint
      args: [
        "--ext", ".js,.jsx",
        "--rule", "mocha/no-exclusive-tests: 2",
        "--parser-options", "{babelOptions: {configFile: '.babelrc'}}"
      ]
      files: frontend/out-web-app/
      additional_dependencies:
      - eslint@^7.10.0
      - eslint-config-prettier@^8.5.0
      - eslint-loader@^4.0.2
      - eslint-plugin-mocha@^8.0.0
      - eslint-plugin-react@^7.12.2
      - eslint-plugin-react-hooks@^4.3.0
      - prettier@^2.5.1
      - "@babel/core@^7.2.2"
      - "@babel/eslint-parser@^7.12.16"
      - "@babel/eslint-plugin@^7.12.13"

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: backend/

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--config", "black.toml"]
        files: backend/, machinelearning/

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg"]
        files: backend/, machinelearning/
        additional_dependencies:
          [
            "flake8-bugbear==22.9.23",
            "flake8-eradicate==1.4.0",
            "flake8-print==5.0.0",
            "flake8-comprehensions==3.10.0",
            "flake8-pytest-style==1.6.0",
          ]
