import os

# Load polish sensitive words into set at the very beggining
polish_sensitive = set()
files = os.listdir("blobs/")
# for num, file in enumerate(files):
#     with open(os.path.join("blobs/", file), "r") as file:
#         for line in file:
#             if len(line) > 4:
#                 polish_sensitive.add(line.rstrip())


regexes_global = {
    "U.S.SOCIAL SECURITY NO": r"(\b(?!000|666|9\d{2})([0-8]\d{2}|7([0-6]\d))([-]?|\s{1})(?!00)\d\d\2(?!0000)\d{4}\b)",
    "IPV4 ADDRESS": r"(^\d{1,3}[.]\d{1,3}[.]\d{1,3}[.]\d{1,3}$)",
    "DATES IN MM/DD/YYYY FORMAT": r"(^([1][12]|[0]?[1-9])[\/-]([3][01]|[12]\d|[0]?[1-9])[\/-](\d{4}|\d{2})$)",
    "MASTERCARD NUMBER": r"(^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$)",
    "VISA CARD NUMBER": r"(\b([4]\d{3}[\s]\d{4}[\s]\d{4}[\s]\d{4}|[4]\d{3}[-]\d{4}[-]\d{4}[-]\d{4}|[4]\d{3}[.]\d{4}[.]\d{4}[.]\d{4}|[4]\d{3}\d{4}\d{4}\d{4})\b)",
    "AMERICAN EXPRESS CARD NUMBER": r"(^3[47][0-9]{13}$)",
    "U.S. ZIP CODE": r"(^((\d{5}-\d{4})|(\d{5})|([A-Z]\d[A-Z]\s\d[A-Z]\d))$)",
    "FILE PATH": r"(\\[^\\]+$	)",
    "DOLLAR AMOUNT": r"(\$[0-9]*.[0-9][0-9])",
    "DATE TYPE 1": r"([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\})",  # 2003-08-06
    "DATE TYPE 2": r"([A-Z][a-z][a-z] [0-9][0-9]*, [0-9]\{4\})",  # Jan 3, 2003
    "DATE TYPE 3": r"(^(\d{1,2})\/(\d{1,2})\/(\d{2}|(19|20)\d{2})$)",  # DD/MM/YY or DD/MM/YYYY or MM/DD/YY or MM/DD/YYYY # noqa E501
    "PHONE NO.": r"((^\+[0-9]{2}|^\+[0-9]{2}\(0\)|^\(\+[0-9]{2}\)\(0\)|^00[0-9]{2}|^0)([0-9]{9}$|[0-9\-\s]{10}$))",
    "CREDIT CARD": r"(^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6011[0-9]{12}|622((12[6-9]|1[3-9][0-9])|([2-8][0-9][0-9])|(9(([0-1][0-9])|(2[0-5]))))[0-9]{10}|64[4-9][0-9]{13}|65[0-9]{14}|3(?:0[0-5]|[68][0-9])[0-9]{11}|3[47][0-9]{13})*)$",
    "HEALTH INSURANCE NO.": r"(^[A-Z]{3}[0-9]{6}[A-Z][0-9]{2}$)",
    "PASSPORT NO.": r"(^[A-Z]{2}[0-9]{7}$)",
    "CELL PHONE NO.": r"(^\+[0-9]{2}[0-9]{9}$)",
    "EMAIL ADDRESS 2": r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)",
    "PESEL": r"(^[0-9]{11}$)",
    "DATE OF BIRTH": r"(^[0-9]{2}/[0-9]{2}/[0-9]{4}$)",
    "ID NO.": r"(^[A-Z]{3}[0-9]{6}$)",
    "NIP": r"(^[0-9]{10}$)",
    "REGON": r"(^[0-9]{9}$)",
    "BANK ACCOUNT NO.": r"(^[0-9]{26}$)",
    "PASSPORT NUMBER": r"(^[A-Z]{2}\d{7}$)",
    "DRIVER'S LICENSE NUMBER": r"(^[A-Z]\d{7}$)",
    "NATIONAL IDENTIFICATION NUMBER": r"(^\d{3}\s\d{3}\s\d{3}$)",
    "NATIONAL INSURANCE NUMBER": r"(^[A-Z]{2}\s\d{6}[A-Z]$)",
    "NATIONAL HEALTH SERVICE NUMBER": r"(^[A-Z]{3}\d{6}[A-Z]{2}$)",
    "CREDIT CARD SECURITY CODE(CVV)": r"(^\d{3,4}$)",
    "DATE OF BIRTH 2": r"(^\d{2}/\d{2}/\d{4}$)",
    "AGE": r"(^[1-9]\d{1,2}$)",
    "HOME ADDRESS": r"(^\d{1,4}\s[A-Z][a-z]+(\s[A-Z][a-z]+)*$)",
    "EMERGENCY CONTACT": r"(^[A-Z][a-z]+(\s[A-Z][a-z]+)\s\d{1,4}\s[A-Z][a-z]+(\s[A-Z][a-z]+)$)",
    "DIFFERENT - MIGHT DELETE": r"(^[A-Z][a-z]+(\s[A-Z][a-z]+)*$)",
    "INCOME": r"(^[1-9]\d*$)",
    "BLOOD TYPE": r"(^[A-Z]$)",
    "PASSWORDS": r"(^[A-Za-z0-9@#$%^&+=]{8,}$)",
    "BANK ACCOUNT NUMBERS": r"(^[A-Z]{2}\d{6,10}$)",
    "CREDIT CARD NUMBERS": r"(^\d{4}\s\d{4}\s\d{4}\s\d{4}$)",
    "INVOICE NUMBERS": r"(^[A-Z]{2,4}-+[0-9]{4,12}$)",
    "TRANSACTION AMOUNTS": r"(^$\d+(,\d{3})*(.\d{2})?$)",
    "PERSONAL IDENTIFICATION NUMBERS (PINS)": r"(^\d{4,6}$)",
    "NUMER PESEL": r"(\b[0-9]{11}\b)",
    "NUMER DOWODU OSOBISTEGO": r"(\b[A-Z]{3}\d{6}\b)",
    "NUMER KARTY KREDYTOWEJ": r"(\b(\d{4}\s){3}\d{4}\b)",
    "NUMER NIP": r"(\b\d{10}\b)",
    "NUMER TELEFONU": r"(\b\+48\s[0-9]{3}\s[0-9]{3}\s[0-9]{3}\b)",
    "NUMER RACHUNKU BANKOWEGO": r"(\b\d{26}\b)",
    "DATA URODZENIA": r"(\b\d{2}\/\d{2}\/\d{4}\b)",
    "IMIĘ/NAZWISKO": r"(\b[A-Z][a-z]+(\s[A-Z][a-z]+)*\b)",
    "NUMER FAKTURY/POLISY/ZAMOWIENIA": r"(\b[A-Z]{2}\d{8}\b)",
    "KWOTA": r"(\b\d+(,\d{3})*(\.\d{2})?\b)",
    "NUMER REGON": r"(\b\d{9}\b)",
    "ADRES FIRMY": r"(\b\d{1,4}\s[A-Z][a-z]+(\s[A-Z][a-z]+)*\b)",
    "KWOTA 2": r"(\b\d+(,\d{3})*(.\d{2})?\b)",
    "NUMER PARTII/SERII": r"(\b\d{1,8}\b)",
    "DATA WAŻNOŚCI": r"(\b\d{2}/\d{2}/\d{4}\b)",
    "EMAIL ADDRESS": r"([\w\.\d]+\@[\w\d]+\.[\w\d]+)",
    # Pattern to match dates in the format "Month Year" (e.g. "January 2021")
    "DATE TYPE 4": r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\b \d{4}",
    # Pattern to match dates in the format "Month-Year" (e.g. "January-2021")
    "DATE TYPE 5": r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)-\d{4}",
    # Pattern to match dates in the format "Month/Year" (e.g. "January/2021")
    "Date type 6" : r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)/\d{4}",
    # Pattern to match dates in the format "MM.YYYY" (e.g. "01.2021")
    "DATE TYPE 7": r"\b(?:0[1-9]|1[0-2])\.[0-9]{4}\b",
    # Pattern to match dates in the format "MM.YYYY-MM.YYYY" (e.g. "01.2021-03.2023")
    "DATE TYPE 8": r"\b(?:0[1-9]|1[0-2])\.[0-9]{4}-(?:0[1-9]|1[0-2])\.[0-9]{4}\b",
    # Pattern to match dates in the format "MM.YYYY-MM.YYYY" (e.g. "01.2021-03.2023")
    "DATE TYPE 9": r"\b(?:0[1-9]|1[0-2])\.[0-9]{4}.*(?:0[1-9]|1[0-2])\.[0-9]{4}\b",
    "DATA TYPE 10": r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{4}",
    "DATA TYPE 11": r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s*-\s*\d{4}",
    "DATA TYPE 12": r"\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s*/\s*\d{4}",
    "DATA TYPE 13": r"\b(?:0[1-9]|1[0-2])\s*\.\s*[0-9]{4}\b",
    "DATA TYPE 14": r"\b(?:0[1-9]|1[0-2])\s*\.\s*[0-9]{4}\s*-\s*(?:0[1-9]|1[0-2])\s*\.\s*[0-9]{4}\b",
    # Pattern to match dates in the format "MM.YYYY" (e.g. "01.2021")
    "DATE TYPE 15": r"\b(?:0[1-9]|1[0-2])/[0-9]{4}\b",
    "DATE TYPE 16": r"\b\d{4}-\d{4}\b",
    "DATE TYPE 17": r"\b\d{4} - \d{4}\b",
    "DATE TYPE 19": r"\b\d{4} \s*-\s* \d{4}\b",
    "DATE TYPE 20": r"\b\d{4}/\d{4}\b",
    "DATE TYPE 21": r"\b\d{4} / \d{4}\b",
    "DATE TYPE 22": r"\b\d{4} \s*/\s* \d{4}\b",
    "DATE TYPE 23": r"\b\d{4}.\d{4}\b",
    "DATE TYPE 24": r"\b\d{4} . \d{4}\b",
    "DATE TYPE 25": r"\b\d{4} \s*.\s* \d{4}\b",
    "DATE TYPE 26": r"\b\d{4}\\\d{4}\b",
    "DATE TYPE 27": r"\b\d{4} \\ \d{4}\b",
    "DATE TYPE 28": r"\b\d{4} \s*\\\s* \d{4}\b",
    "DATE TYPE 29": r"\b\d{4}|\d{4}\b",
    "DATE TYPE 30": r"\b\d{4} | \d{4}\b",
    "DATE TYPE 31": r"\b\d{4} \s*|\s* \d{4}\b"
}


default_regexes = [
    "NUMER PESEL",
    "NUMER DOWODU OSOBISTEGO",
    "NUMER KARTY KREDYTOWEJ",
    "NUMER NIP",
    "NUMER TELEFONU",
    "NUMER RACHUNKU BANKOWEGO",
    "EMAIL ADDRESS",
    "HOME ADDRESS",
    "DATE TYPE 1",
    "DATE TYPE 2",
    "DATE TYPE 3",
    "DATE TYPE 4",
    "DATE TYPE 5",
    "DATE TYPE 6",
    "DATE TYPE 7",
    "DATE TYPE 8",
    "DATE TYPE 9",
    "DATE TYPE 10",
    "DATE TYPE 11",
    "DATE TYPE 12",
    "DATE TYPE 13",
    "DATE TYPE 14",
    "DATE TYPE 15",
    "DATE TYPE 15",
    "DATE TYPE 16",
    "DATE TYPE 17",
    "DATE TYPE 19",
    "DATE TYPE 20",
    "DATE TYPE 21",
    "DATE TYPE 22",
    "DATE TYPE 23",
    "DATE TYPE 24",
    "DATE TYPE 25",
    "DATE TYPE 26",
    "DATE TYPE 27",
    "DATE TYPE 28",
    "DATE TYPE 29",
    "DATE TYPE 30",
    "DATE TYPE 31",
]
